language: ruby

sudo: false

addons:
    apt:
        packages:
        - ghostscript

rvm:
  - 2.4.0
	- 2.5.1

gemfile:
  - Gemfile

notifications:
  email:
    - jacob.hammack@hammackj.com
  irc: "irc.freenode.org#risu"

before_install:
  - gem --version
